<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Clicking on SignIn ]]>
    </line>
    <line>
      <![CDATA[Passing Mo No]]>
    </line>
    <line>
      <![CDATA[Clicking on submit button]]>
    </line>
    <line>
      <![CDATA[Passing password]]>
    </line>
    <line>
      <![CDATA[Clicking on submit button]]>
    </line>
    <line>
      <![CDATA[Clicking on OK]]>
    </line>
    <line>
      <![CDATA[Clicking on close button]]>
    </line>
    <line>
      <![CDATA[Validating Profile name]]>
    </line>
  </reporter-output>
  <suite started-at="2022-12-06T17:36:00 IST" name="Default suite" finished-at="2022-12-06T17:36:26 IST" duration-ms="26313">
    <groups>
    </groups>
    <test started-at="2022-12-06T17:36:00 IST" name="Default test" finished-at="2022-12-06T17:36:26 IST" duration-ms="26313">
      <class name="com.neoStox.testCases.TC_004">
        <test-method is-config="true" signature="Setup()[pri:0, instance:com.neoStox.testCases.TC_004@d9345cd]" started-at="2022-12-06T17:36:00 IST" name="Setup" finished-at="2022-12-06T17:36:02 IST" duration-ms="2793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method is-config="true" signature="login2()[pri:0, instance:com.neoStox.testCases.TC_004@d9345cd]" started-at="2022-12-06T17:36:02 IST" name="login2" finished-at="2022-12-06T17:36:22 IST" duration-ms="19156" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Clicking on SignIn ]]>
            </line>
            <line>
              <![CDATA[Passing Mo No]]>
            </line>
            <line>
              <![CDATA[Clicking on submit button]]>
            </line>
            <line>
              <![CDATA[Passing password]]>
            </line>
            <line>
              <![CDATA[Clicking on submit button]]>
            </line>
            <line>
              <![CDATA[Clicking on OK]]>
            </line>
            <line>
              <![CDATA[Clicking on close button]]>
            </line>
          </reporter-output>
        </test-method> <!-- login2 -->
        <test-method signature="ValidateProfileName()[pri:0, instance:com.neoStox.testCases.TC_004@d9345cd]" started-at="2022-12-06T17:36:22 IST" name="ValidateProfileName" finished-at="2022-12-06T17:36:22 IST" duration-ms="70" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [null] but found [Rs.5,00,000.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [Rs.5,00,000.00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.neoStox.testCases.TC_004.ValidateProfileName(TC_004.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Validating Profile name]]>
            </line>
          </reporter-output>
        </test-method> <!-- ValidateProfileName -->
        <test-method is-config="true" signature="LogoutFromNeoStox()[pri:0, instance:com.neoStox.testCases.TC_004@d9345cd]" started-at="2022-12-06T17:36:22 IST" name="LogoutFromNeoStox" finished-at="2022-12-06T17:36:25 IST" duration-ms="3128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromNeoStox -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.neoStox.testCases.TC_004@d9345cd]" started-at="2022-12-06T17:36:25 IST" name="tearDown" finished-at="2022-12-06T17:36:26 IST" duration-ms="1137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.neoStox.testCases.TC_004 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
